input_path: ../data_process/example_input.jsonl
output_path: results/TokenLengthScorer/
num_gpu: 0
num_gpu_per_job: 0
scorers:
- name: TokenLengthScorer
  encoder: o200k_base
  fields:
  - instruction
  - input
  - output
  max_workers: 128
