input_path: ../data_process/example_input.jsonl
output_path: results/AnswerProbScorer/
num_gpu: 4
num_gpu_per_job: 1
scorers:
- name: AnswerProbScorer
  model: Qwen/Qwen3-8B
  max_length: 4096
  batch_size: 2
  num_gpu_per_job: 1
  case_sensitive: true
