input_path: ../data_process/example_input.jsonl
output_path: results/ApsScorer/
num_gpu: 4
num_gpu_per_job: 1
scorers:
- name: ApsScorer
  embedding_path: ../data_process/mock_embedding_128x512.npy
  similarity_metric: euclidean
  max_workers: 128
  num_gpu_per_job: 0
  sample_pairs: 1000
