input_path: ../data_process/example_input.jsonl
output_path: results/AskLlmScorer/
num_gpu: 4
num_gpu_per_job: 1
scorers:
- name: AskLlmScorer
  model: Qwen/Qwen3-8B
  max_length: 2048
  prompt: 'Is the following data high quality? Please answer yes or no.


    '
  yes_token: 'yes'
  batch_size: 8
  num_gpu_per_job: 1
