input_path: /mnt/petrelfs/gaoxin/OpenDataArena-Tool/data_scorer/model_based/data/failratedemodata.jsonl
output_path: results/demo_per_scorer_advanced/
num_gpu: 4
num_gpu_per_job: 1
scorers:
- name: AskLlmScorer
  model: /mnt/dhwfile/raise/data-leaderboard/model/gaoxin/Qwen3-8B
  max_length: 2048
  prompt: 'Is the following data high quality? Please answer yes or no.


    '
  yes_token: 'yes'
  batch_size: 8
  num_gpu_per_job: 1
