input_path: ../data_process/example_input.jsonl
output_path: results/AtheneScorer/
num_gpu: 4
num_gpu_per_job: 1
scorers:
- name: AtheneScorer
  model: Nexusflow/Athene-RM-8B
  batch_size: 8
  max_length: 4096
  num_gpu_per_job: 1
