input_path: ../data_process/example_input.jsonl
output_path: results/CleanlinessScorer/
num_gpu: 4
num_gpu_per_job: 1
scorers:
- name: CleanlinessScorer
  model: opendatalab/meta-rater-cleanliness-rating
  batch_size: 16
  max_model_len: 1024
  num_gpu_per_job: 1
