input_path: ../data_process/example_input.jsonl
output_path: results/DeitaQScorer/
num_gpu: 4
num_gpu_per_job: 1
scorers:
- name: DeitaQScorer
  model: hkust-nlp/deita-quality-scorer
  max_length: 2048
  batch_size: 8
  num_gpu_per_job: 1
