input_path: ../data_process/example_input.jsonl
output_path: results/EffectiveRankScorer/
num_gpu: 4
num_gpu_per_job: 1
scorers:
- name: EffectiveRankScorer
  model: Qwen/Qwen3-1.7B
  max_length: 2048
  start_layer_index: 10
  num_layers: 2
  num_gpu_per_job: 1
