input_path: ../data_process/example_input.jsonl
output_path: results/FacilityLocationScorer/
num_gpu: 4
num_gpu_per_job: 1
scorers:
- name: FacilityLocationScorer
  embedding_path: ../data_process/mock_embedding_128x512.npy
  subset_embeddings_path: ../data_process/mock_subset_embedding_64x512.npy
  distance_metric: cosine
  max_workers: 128
  num_gpu_per_job: 0
