input_path: ../data_process/example_input.jsonl
output_path: results/InstagScorer/
num_gpu: 4
num_gpu_per_job: 1
scorers:
- name: InstagScorer
  model: OFA-Sys/InsTagger
  max_new_tokens: 512
  batch_size: 8
  num_gpu_per_job: 1
