input_path: ../data_process/example_input.jsonl
output_path: results/KNNScorer/
num_gpu: 4
num_gpu_per_job: 1
scorers:
- name: KNNScorer
  k: 10
  distance_metric: cosine
  max_workers: 128
  embedding_path: ../data_process/mock_embedding_128x512.npy
  num_gpu_per_job: 0
