input_path: ../data_process/example_input.jsonl
output_path: results/demo_per_scorer_advanced/
num_gpu: 4
num_gpu_per_job: 1
scorers:
- name: LogDetDistanceScorer
  embedding_path: ../data_process/mock_embedding_128x512.npy
  ridge_alpha: 1e-10
  num_gpu_per_job: 0
  max_workers: 128
