input_path: ../data_process/example_input.jsonl
output_path: results/NovelSumScorer/
num_gpu: 4
num_gpu_per_job: 1
scorers:
- name: NovelSumScorer
  use_gpu_faiss: false
  embedding_path: ../data_process/mock_embedding_128x512.npy
  dense_ref_path: results/NovelSumScorer/
  density_powers:
  - 0
  - 0.25
  - 0.5
  neighbors:
  - 5
  - 10
  distance_powers:
  - 0
  - 1
  - 2
  num_gpu_per_job: 0
