input_path: /mnt/petrelfs/gaoxin/OpenDataArena-Tool/data_scorer/model_based/data/failratedemodata.jsonl
output_path: results/demo_per_scorer_advanced/
num_gpu: 4
num_gpu_per_job: 1
scorers:
- name: PartitionEntropyScorer
  num_clusters: 22
  num_gpu_per_job: 0
