input_path: ../data_process/example_input.jsonl
output_path: results/ProfessionalismScorer/
num_gpu: 4
num_gpu_per_job: 1
scorers:
- name: ProfessionalismScorer
  model: meta-rater-professionalism-rating
  batch_size: 16
  max_length: 2048
  num_gpu_per_job: 1
