input_path: /mnt/petrelfs/gaoxin/OpenDataArena-Tool/data_scorer/model_based/data/failratedemodata.jsonl
output_path: results/demo_per_scorer_advanced/
num_gpu: 4
num_gpu_per_job: 1
scorers:
- name: QuRateScorer
  model: /share/wulijun/gaoxin/local_models/QuRater-1.3B
  labels:
  - writing_style
  - required_expertise
  - facts_and_trivia
  - educational_value
  chunk_size: 512
  batch_size: 8
  device_batch_size: 16
  num_gpu_per_job: 1
