input_path: ../data_process/example_input.jsonl
output_path: results/QuRateScorer/
num_gpu: 4
num_gpu_per_job: 1
scorers:
- name: QuRateScorer
  model: princeton-nlp/QuRater-1.3B
  labels:
  - writing_style
  - required_expertise
  - facts_and_trivia
  - educational_value
  chunk_size: 512
  batch_size: 8
  device_batch_size: 16
  num_gpu_per_job: 1
