input_path: /mnt/petrelfs/gaoxin/OpenDataArena-Tool/data_scorer/model_based/data/failratedemodata.jsonl
output_path: results/demo_per_scorer_advanced/
num_gpu: 4
num_gpu_per_job: 1
scorers:
- name: RadiusScorer
  embedding_path: /mnt/petrelfs/gaoxin/OpenDataArena-Tool/data_scorer/model_based/results1/ClusterInertiaScorer/mock_embeddings.npy
  max_workers: 128
  num_gpu_per_job: 0
