input_path: ../data_process/example_input.jsonl
output_path: results/ReadabilityScorer/
num_gpu: 4
num_gpu_per_job: 1
scorers:
- name: ReadabilityScorer
  model: opendatalab/meta-rater-readability-rating
  batch_size: 16
  max_model_len: 2048
  num_gpu_per_job: 1
