input_path: ../data_process/example_input.jsonl
output_path: results/RMDeBERTaScorer/
num_gpu: 4
num_gpu_per_job: 1
scorers:
- name: RMDeBERTaScorer
  model: OpenAssistant/reward-model-deberta-v3-large-v2
  max_length: 4096
  batch_size: 8
  num_gpu_per_job: 1
