input_path: ../data_process/example_input.jsonl
output_path: results/SelectitTokenScorer/
num_gpu: 4
num_gpu_per_job: 1
scorers:
- name: SelectitTokenScorer
  model: Qwen/Qwen3-8B
  max_length: 512
  batch_size: 8
  rp_file: ../model_based/scorers/SelectIT_rating_prompt.txt
  k: 1
  alpha: 0.2
  num_gpu_per_job: 1
