input_path: ../data_process/example_input.jsonl
output_path: results/SkyworkRewardScorer/
num_gpu: 4
num_gpu_per_job: 1
scorers:
- name: SkyworkRewardScorer
  model: Skywork/Skywork-Reward-V2-Llama-3.1-8B-40M
  batch_size: 8
  max_length: 1024
  num_gpu_per_job: 1
