input_path: ../data_process/example_input.jsonl
output_path: results/StrLengthScorer/
num_gpu: 4
num_gpu_per_job: 1
scorers:
- name: StrLengthScorer
  fields:
  - instruction
  - input
  - output
  max_workers: 256
  num_gpu_per_job: 0
