input_path: ../data_process/example_input.jsonl
output_path: results/TextbookScorer/
num_gpu: 4
num_gpu_per_job: 1
scorers:
- name: TextbookScorer
  model: llm-data-textbook-quality-fasttext-classifier-v2
  max_length: 512
  batch_size: 8
  num_gpu_per_job: 1
