input_path: /mnt/petrelfs/gaoxin/OpenDataArena-Tool/data_scorer/model_based/data/failratedemodata.jsonl
output_path: results/demo_per_scorer_advanced/
num_gpu: 4
num_gpu_per_job: 1
scorers:
- name: ThinkingProbScorer
  model: /mnt/dhwfile/raise/data-leaderboard/model/gaoxin/AdaptThink-7B-delta0.05
  batch_size: 128
  num_gpu_per_job: 1
