input_path: ../data_process/example_input_code.jsonl
output_path: results/TsPythonScorer/
num_gpu: 4
num_gpu_per_job: 1
scorers:
- name: TsPythonScorer
  field: output
  max_workers: 256
  num_gpu_per_job: 0
