input_path: ../data_process/example_input_UniEvalDialogScorer.jsonl
output_path: results/demo_per_scorer_advanced/
num_gpu: 4
num_gpu_per_job: 1
scorers:
- name: UniEvalDialogScorer
  model: MingZhong/unieval-dialog
  max_length: 1024
  batch_size: 2
  overall: true
  num_gpu_per_job: 1
