input_path: ../data_process/example_input.jsonl
output_path: results/UniEvalSumScorer/
num_gpu: 4
num_gpu_per_job: 1
scorers:
- name: UniEvalSumScorer
  model: MingZhong/unieval-sum
  max_length: 1024
  batch_size: 4
  overall: true
  num_gpu_per_job: 1
