input_path: ../data_process/example_input_UniEvalFactScorer.jsonl
output_path: results/UniqueNgramScorer/
num_gpu: 4
num_gpu_per_job: 1
scorers:
- name: UniqueNgramScorer
  n: 2
  max_workers: 256
  num_gpu_per_job: 0
