### model
model_name_or_path: Qwen/Qwen3-VL-8B-Instruct 
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
seed: ${SEED}
freeze_vision_tower: true
freeze_multi_modal_projector: true
freeze_language_model: false
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: ${DATASET} # HoneyBee
template: qwen3_vl # [qwen3_vl](by default it's with thinking) or [qwen3_vl_nothink] --> {./LLaMA-Factory/src/llamafactory/data/template.py line 1933}
packing: true
cutoff_len: 12288
max_samples: 10000000
overwrite_cache: true
preprocessing_num_workers: 64
dataloader_num_workers: 4

### output
output_dir: saves/qwen3vl-8b/full/sft-${DATASET}/seed-${SEED}
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: true
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null